#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Mesh generation
./Allclean
opv1812
runApplication blockMesh 
cp -r 0.orig 0
runApplication checkMesh -allGeometry -allTopology
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite
rm -r constant/polyMesh
rm constant/cellToRegion
runApplication initAlphaField -region fluid
runApplication setFields -region fluid

#------------------------------------------------------------------------------
